list structure finalized
DilsherB/TODO-List pull request #1
Opened 2023-02-21 12:25 UTC by DilsherB

In this branch i did the following:
1. index.html added with basic stuff.
2. populate tasks from array of objects by looping through the array.
3. show and hide the delete icon for every todo item.
4. apply styling to make it more user friendly.

2023-02-21 12:39 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @DilsherB , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that has some failing linter checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-21 13:24 UTC, youmari requested changes
Hi @DilsherB , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 13:24 UTC, youmari commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
- [ ] it would be better to make sure that MIT section  and `MIT` link is working and it should take you to the License of the project in order for your project will be professional

2023-02-21 13:34 UTC, DilsherB commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
@youmari can you please guide me how to create MIT license.

2023-02-21 15:15 UTC, youmari commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
@DilsherB it's already created on your project you just need to add the License section with link that will navigate to the license by adding this at the end of the readme file 
```markdown
## 📝 License <a name="license"></a>

This project is [MIT](./LICENSE) licensed.
```

2023-02-21 16:10 UTC, DilsherB commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
@youmari Thanks for your guidance.
I have updated readme. 
now please approve it to submit.

2023-02-22 07:06 UTC, DilsherB commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
@youmari dear you have still not approved it

2023-02-22 08:20 UTC, youmari commented on README.md
> -Feel free to check the [issues page](https://github.com/DilsherB/webpack-demo/issues).
@DilsherB you should send for another review and then a reviewer will review it

2023-02-22 14:31 UTC, julie-ify approved these changes
Hi @DilsherB,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 14:35 UTC, merged